
   /******************************************************************************************************************************
 File Name      : iot_configs.h
 Description    : This file as Header for iot configuration
 Author         : Omar Sameh
 Tester         :
 Device(s)      : ESP32S2
 Creation Date  : 1/1/2024
 Testing Date   :
 @COPYRIGHT 2016 El-ARABY Research and development center.
 all rights reserved
*********************************************************************************************************************************/
#ifndef IOT_CONFIGS_H
#define IOT_CONFIGS_H

//FOTA PRODUCT URL
#define FOTA_SERVER_URL "https://tornadofotaserver.000webhostapp.com/"
#define FOTA_SERVER_FIRMWARE_ENDPOINT "/upload.php?device=e"
#define FOTA_DEVICE_FOLDER "/uploads/e/"

// Enable macro IOT_CONFIG_USE_X509_CERT to use an x509 certificate to authenticate the IoT device.
// The two main modes of authentication are through SAS tokens (automatically generated by the
// sample using the provided device symmetric key) or through x509 certificates. Please choose the
// appropriate option according to your device authentication mode.

//#define IOT_CONFIG_USE_X509_CERT

#ifdef IOT_CONFIG_USE_X509_CERT

/*
 * Please set the define IOT_CONFIG_DEVICE_CERT below with
 * the content of your device x509 certificate.
 *
 * Example:
 * #define IOT_CONFIG_DEVICE_CERT "-----BEGIN CERTIFICATE-----
"  * "MIIBJDCBywIUfeHrebBVa2eZAbouBgACp9R3BncwCgYIKoZIzj0EAwIwETEPMA0G
"  * "A1UEAwwGRFBTIENBMB4XDTIyMDMyMjazMTAzN1oXDTIzMDMyMjIzMTAzN1owGTEX
"  * "MBUGA1UEAwwOY29udG9zby1kZXZpY2UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
"  * .......
 * "YmGzdaHTb6P1W+p+jmc+jJn1MAoGCXqGSM49BAMCA0gAMEUCIEnbEMsAdGFroMwl
"  * "vTfQahwsxN3xink9z1gtirrjQlqDAiEAyU+6TUJcG6d9JF+uJqsLFpsbbF3IzGAw
"  * "yC+koNRC0MU=
"  * "-----END CERTIFICATE-----"
 *
 */
#define IOT_CONFIG_DEVICE_CERT "e"


/*
 * Please set the define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY below with
 * the content of your device x509 private key.
 *
 * Example:
 *
 * #define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY "-----BEGIN EC PRIVATE KEY-----
"  * "MHcCAQEEIKGXkMMiO9D7jYpUjUGTBn7gGzeKPeNzCP83wbfQfLd9obAoGCCqGSM49
"  * "AwEHoUQDQgAEU6nQoYbjgJvBwaeD6MyAYmOSDg0QhEdyyV337qrlIbDEKvFsn1El
"  * "yRabc4dNp2Jhs3Xh02+j9Vvqfo5nPoyZ9Q==
"  * "-----END EC PRIVATE KEY-----"
 *
 * Note the type of key may different in your case. Such as BEGIN PRIVATE KEY
 * or BEGIN RSA PRIVATE KEY.
 *
 */
#define IOT_CONFIG_DEVICE_CERT_PRIVATE_KEY "e"

#endif // IOT_CONFIG_USE_X509_CERT

// Azure IoT
#define IOT_CONFIG_IOTHUB_FQDN "e"

// Use device key if not using certificates
#ifndef IOT_CONFIG_USE_X509_CERT
#define IOT_CONFIG_DEVICE_KEY "e"
#endif // IOT_CONFIG_USE_X509_CERT

// Publish 1 message every 2 seconds
#define TELEMETRY_FREQUENCY_MILLISECS 2000

#define AZURE_SDK_CLIENT_USER_AGENT "c%2F" AZ_SDK_VERSION_STRING "(ard;esp32)"

// Utility macros and defines
#define sizeofarray(a) (sizeof(a) / sizeof(a[0])) // Macro to get the size of an array
#define NTP_SERVERS "pool.ntp.org", "time.nist.gov" // NTP server addresses
#define MQTT_QOS1 1                 // MQTT Quality of Service level
#define DO_NOT_RETAIN_MSG 0         // MQTT retain message flag
#define SAS_TOKEN_DURATION_IN_MINUTES 60 // Duration of SAS token validity in minutes
#define UNIX_TIME_NOV_13_2017 1510592825   // Reference UNIX timestamp

#define PST_TIME_ZONE -8                       // Pacific Standard Time (PST) time zone
#define PST_TIME_ZONE_DAYLIGHT_SAVINGS_DIFF 1  // Daylight Saving Time (DST) difference

#define GMT_OFFSET_SECS (PST_TIME_ZONE * 3600)                               // GMT offset without DST
#define GMT_OFFSET_SECS_DST ((PST_TIME_ZONE + PST_TIME_ZONE_DAYLIGHT_SAVINGS_DIFF) * 3600) // GMT offset with DST

// Define the EEPROM addresses for storing data
#define EEPROM_ADDR_WIFI_SSID 0
#define EEPROM_ADDR_WIFI_PASSWORD (EEPROM_ADDR_WIFI_SSID + sizeof(ssid))
#define EEPROM_ADDR_ADMIN_USERNAME (EEPROM_ADDR_WIFI_PASSWORD + sizeof(password))
#define EEPROM_ADDR_ADMIN_PASSWORD (EEPROM_ADDR_ADMIN_USERNAME + sizeof(adminUsername))
#define EEPROM_ADDR_ADMIN_MOBILE (EEPROM_ADDR_ADMIN_PASSWORD + sizeof(adminPassword))

#define GREEN_LED_PIN e   // Replace with the actual GPIO pin number for the green LED
#define RED_LED_PIN e     // Replace with the actual GPIO pin number for the red LED
#define BLUE_LED_PIN 2    // Replace with the actual GPIO pin number for the blue LED

// Twilio configuration for (OTP Code)
#define TWILIO_ACCOUNT_SID "AC3bb09af01fe7e803765415104cb35809"
#define TWILIO_AUTH_TOKEN "3758854dfcf330775231ff1763a23119"
#define TWILIO_PHONE_NUMBER "+14328472138"

#define TWILIO_API_URL "api.twilio.com"
#define TWILIO_API_PORT 443

// Google Map apiKey 
#define apiKey "680393823aa050"
#define thisPage "/geolocation/v1/geolocate?key="
#define Host "www.googleapis.com"

#endif
    